---
title: "by-county-nc"
output: html_document
date: "2022-10-18"
---

# Install dependencies
```{r}
install.packages("tidyverse")
install.packages("fuzzyjoin")
install.packages("dplyr")
library(tidyverse)
library(dplyr)
library(fuzzyjoin)
```

```{r}
all_stats = read.delim("./ncvoter_Statewide.txt", sep = "\t")
```

# Import datasets
```{r}
DURHAM_voters <- filter(all_stats ,county_desc == "DURHAM")
NASH_voters <- filter(all_stats ,county_desc == "NASH")
NEW_HANOVER_voters <- filter(all_stats ,county_desc == "NEW HANOVER")
RANDOLPH_voters <- filter(all_stats ,county_desc == "RANDOLPH")
ROBESON_voters <- filter(all_stats ,county_desc == "ROBESON")
SCOTLAND_voters <- filter(all_stats ,county_desc == "SCOTLAND")
MECKLENBURG_voters <- filter(all_stats ,county_desc == "MECKLENBURG")
```


# DURHAM STATS
```{r}
DURHAM_stats <- matrix(c(count(filter(DURHAM_voters, party_cd == "DEM")), count(filter(DURHAM_voters, party_cd == "REP")), count(filter(DURHAM_voters, party_cd == "UNA")), '', '', '', count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "A")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "A")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "A")), count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "B")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "B")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "B")), count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "I")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "I")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "I")), count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "M")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "M")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "M")), count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "O")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "O")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "O")), count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "P")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "P")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "P")), count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "U")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "U")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "U")), count(filter(DURHAM_voters, party_cd == "DEM" & race_code == "W")), count(filter(DURHAM_voters, party_cd == "REP" & race_code == "W")), count(filter(DURHAM_voters, party_cd == "UNA" & race_code == "W")), " ", " ", " ", count(filter(DURHAM_voters, party_cd == "DEM" & ethnic_code == "HL")), count(filter(DURHAM_voters, party_cd == "REP" & ethnic_code == "HL")), count(filter(DURHAM_voters, party_cd == "UNA" & ethnic_code == "HL")), count(filter(DURHAM_voters, party_cd == "DEM" & ethnic_code == "NL")), count(filter(DURHAM_voters, party_cd == "REP" & ethnic_code == "NL")), count(filter(DURHAM_voters, party_cd == "UNA" & ethnic_code == "NL")), count(filter(DURHAM_voters, party_cd == "DEM" & ethnic_code == "UN")), count(filter(DURHAM_voters, party_cd == "REP" & ethnic_code == "UN")), count(filter(DURHAM_voters, party_cd == "UNA" & ethnic_code == "UN")), "", "","" , count(filter(DURHAM_voters, party_cd == "DEM" & age_at_year_end <= "30")), count(filter(DURHAM_voters, party_cd == "REP" & age_at_year_end <= "30")), count(filter(DURHAM_voters, party_cd == "UNA" & age_at_year_end <= "30")), count(filter(DURHAM_voters, party_cd == "DEM" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(DURHAM_voters, party_cd == "REP" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(DURHAM_voters, party_cd == "UNA" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(DURHAM_voters, party_cd == "DEM" & age_at_year_end > "64")), count(filter(DURHAM_voters, party_cd == "REP" & age_at_year_end > "64")), count(filter(DURHAM_voters, party_cd == "UNA" & age_at_year_end > "64")), " ", " ", " ", count(filter(DURHAM_voters, party_cd == "DEM" & gender_code == "F")), count(filter(DURHAM_voters, party_cd == "REP" & gender_code == "F")), count(filter(DURHAM_voters, party_cd == "UNA" & gender_code == "F")), count(filter(DURHAM_voters, party_cd == "DEM" & gender_code == "M")), count(filter(DURHAM_voters, party_cd == "REP" & gender_code == "M")), count(filter(DURHAM_voters, party_cd == "UNA" & gender_code == "M")), " ", " ", " "," ", " ", count(filter(DURHAM_voters))),ncol=3,byrow=TRUE)
colnames(DURHAM_stats) <- c("DEM", "REP", "UNA")
rownames(DURHAM_stats) <- c("ALL", "**race**","ASIAN","BLACK or AFRICAN AMERICAN", "AMERICAN INDIAN or ALASKA NATIVE",  "TWO or MORE RACES", "OTHER", "NATIVE HAWAIIAN or PACIFIC ISLANDER", "UNDESIGNATED", "WHITE", "**ethnicity**", "HISPANIC or LATINO", "NOT HISPANIC or NOT LATINO", "UNDESIGNATED", "**age**", "LESS 30", "BETWEEN 30 & 65","MORE 65", "**sex**","FEMALE", "MALE", "**count total**","TOTAL")
# DURHAM_stats <- as.table(DURHAM_stats)
DURHAM_stats
```

# MECKLENBURG STATS
```{r}
MECKLENBURG_stats <- matrix(c(count(filter(MECKLENBURG_voters, party_cd == "DEM")), count(filter(MECKLENBURG_voters, party_cd == "REP")), count(filter(MECKLENBURG_voters, party_cd == "UNA")), '', '', '', count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "A")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "A")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "A")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "B")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "B")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "B")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "I")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "I")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "I")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "M")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "M")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "M")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "O")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "O")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "O")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "P")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "P")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "P")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "U")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "U")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "U")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & race_code == "W")), count(filter(MECKLENBURG_voters, party_cd == "REP" & race_code == "W")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & race_code == "W")), " ", " ", " ", count(filter(MECKLENBURG_voters, party_cd == "DEM" & ethnic_code == "HL")), count(filter(MECKLENBURG_voters, party_cd == "REP" & ethnic_code == "HL")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & ethnic_code == "HL")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & ethnic_code == "NL")), count(filter(MECKLENBURG_voters, party_cd == "REP" & ethnic_code == "NL")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & ethnic_code == "NL")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & ethnic_code == "UN")), count(filter(MECKLENBURG_voters, party_cd == "REP" & ethnic_code == "UN")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & ethnic_code == "UN")), "", "","" , count(filter(MECKLENBURG_voters, party_cd == "DEM" & age_at_year_end <= "30")), count(filter(MECKLENBURG_voters, party_cd == "REP" & age_at_year_end <= "30")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & age_at_year_end <= "30")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(MECKLENBURG_voters, party_cd == "REP" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & age_at_year_end > "64")), count(filter(MECKLENBURG_voters, party_cd == "REP" & age_at_year_end > "64")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & age_at_year_end > "64")), " ", " ", " ", count(filter(MECKLENBURG_voters, party_cd == "DEM" & gender_code == "F")), count(filter(MECKLENBURG_voters, party_cd == "REP" & gender_code == "F")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & gender_code == "F")), count(filter(MECKLENBURG_voters, party_cd == "DEM" & gender_code == "M")), count(filter(MECKLENBURG_voters, party_cd == "REP" & gender_code == "M")), count(filter(MECKLENBURG_voters, party_cd == "UNA" & gender_code == "M")), " ", " ", " "," ", " ", count(filter(MECKLENBURG_voters))),ncol=3,byrow=TRUE)
colnames(MECKLENBURG_stats) <- c("DEM", "REP", "UNA")
rownames(MECKLENBURG_stats) <- c("ALL", "**race**","ASIAN","BLACK or AFRICAN AMERICAN", "AMERICAN INDIAN or ALASKA NATIVE",  "TWO or MORE RACES", "OTHER", "NATIVE HAWAIIAN or PACIFIC ISLANDER", "UNDESIGNATED", "WHITE", "**ethnicity**", "HISPANIC or LATINO", "NOT HISPANIC or NOT LATINO", "UNDESIGNATED", "**age**", "LESS 30", "BETWEEN 30 & 65","MORE 65", "**sex**","FEMALE", "MALE", "**count total**","TOTAL")
# MECKLENBURG_stats <- as.table(MECKLENBURG_stats)
MECKLENBURG_stats
```

# NASH STATS
```{r}
NASH_stats <- matrix(c(count(filter(NASH_voters, party_cd == "DEM")), count(filter(NASH_voters, party_cd == "REP")), count(filter(NASH_voters, party_cd == "UNA")), '', '', '', count(filter(NASH_voters, party_cd == "DEM" & race_code == "A")), count(filter(NASH_voters, party_cd == "REP" & race_code == "A")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "A")), count(filter(NASH_voters, party_cd == "DEM" & race_code == "B")), count(filter(NASH_voters, party_cd == "REP" & race_code == "B")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "B")), count(filter(NASH_voters, party_cd == "DEM" & race_code == "I")), count(filter(NASH_voters, party_cd == "REP" & race_code == "I")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "I")), count(filter(NASH_voters, party_cd == "DEM" & race_code == "M")), count(filter(NASH_voters, party_cd == "REP" & race_code == "M")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "M")), count(filter(NASH_voters, party_cd == "DEM" & race_code == "O")), count(filter(NASH_voters, party_cd == "REP" & race_code == "O")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "O")), count(filter(NASH_voters, party_cd == "DEM" & race_code == "P")), count(filter(NASH_voters, party_cd == "REP" & race_code == "P")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "P")), count(filter(NASH_voters, party_cd == "DEM" & race_code == "U")), count(filter(NASH_voters, party_cd == "REP" & race_code == "U")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "U")), count(filter(NASH_voters, party_cd == "DEM" & race_code == "W")), count(filter(NASH_voters, party_cd == "REP" & race_code == "W")), count(filter(NASH_voters, party_cd == "UNA" & race_code == "W")), " ", " ", " ", count(filter(NASH_voters, party_cd == "DEM" & ethnic_code == "HL")), count(filter(NASH_voters, party_cd == "REP" & ethnic_code == "HL")), count(filter(NASH_voters, party_cd == "UNA" & ethnic_code == "HL")), count(filter(NASH_voters, party_cd == "DEM" & ethnic_code == "NL")), count(filter(NASH_voters, party_cd == "REP" & ethnic_code == "NL")), count(filter(NASH_voters, party_cd == "UNA" & ethnic_code == "NL")), count(filter(NASH_voters, party_cd == "DEM" & ethnic_code == "UN")), count(filter(NASH_voters, party_cd == "REP" & ethnic_code == "UN")), count(filter(NASH_voters, party_cd == "UNA" & ethnic_code == "UN")), "", "","" , count(filter(NASH_voters, party_cd == "DEM" & age_at_year_end <= "30")), count(filter(NASH_voters, party_cd == "REP" & age_at_year_end <= "30")), count(filter(NASH_voters, party_cd == "UNA" & age_at_year_end <= "30")), count(filter(NASH_voters, party_cd == "DEM" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(NASH_voters, party_cd == "REP" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(NASH_voters, party_cd == "UNA" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(NASH_voters, party_cd == "DEM" & age_at_year_end > "64")), count(filter(NASH_voters, party_cd == "REP" & age_at_year_end > "64")), count(filter(NASH_voters, party_cd == "UNA" & age_at_year_end > "64")), " ", " ", " ", count(filter(NASH_voters, party_cd == "DEM" & gender_code == "F")), count(filter(NASH_voters, party_cd == "REP" & gender_code == "F")), count(filter(NASH_voters, party_cd == "UNA" & gender_code == "F")), count(filter(NASH_voters, party_cd == "DEM" & gender_code == "M")), count(filter(NASH_voters, party_cd == "REP" & gender_code == "M")), count(filter(NASH_voters, party_cd == "UNA" & gender_code == "M")), " ", " ", " "," ", " ", count(filter(NASH_voters))),ncol=3,byrow=TRUE)
colnames(NASH_stats) <- c("DEM", "REP", "UNA")
rownames(NASH_stats) <- c("ALL", "**race**","ASIAN","BLACK or AFRICAN AMERICAN", "AMERICAN INDIAN or ALASKA NATIVE",  "TWO or MORE RACES", "OTHER", "NATIVE HAWAIIAN or PACIFIC ISLANDER", "UNDESIGNATED", "WHITE", "**ethnicity**", "HISPANIC or LATINO", "NOT HISPANIC or NOT LATINO", "UNDESIGNATED", "**age**", "LESS 30", "BETWEEN 30 & 65","MORE 65", "**sex**","FEMALE", "MALE", "**count total**","TOTAL")
# NASH_stats <- as.table(NASH_stats)
NASH_stats
```

# NEW_HANOVER STATS
```{r}
NEW_HANOVER_stats <- matrix(c(count(filter(NEW_HANOVER_voters, party_cd == "DEM")), count(filter(NEW_HANOVER_voters, party_cd == "REP")), count(filter(NEW_HANOVER_voters, party_cd == "UNA")), '', '', '', count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "A")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "A")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "A")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "B")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "B")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "B")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "I")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "I")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "I")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "M")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "M")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "M")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "O")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "O")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "O")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "P")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "P")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "P")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "U")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "U")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "U")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & race_code == "W")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & race_code == "W")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & race_code == "W")), " ", " ", " ", count(filter(NEW_HANOVER_voters, party_cd == "DEM" & ethnic_code == "HL")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & ethnic_code == "HL")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & ethnic_code == "HL")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & ethnic_code == "NL")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & ethnic_code == "NL")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & ethnic_code == "NL")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & ethnic_code == "UN")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & ethnic_code == "UN")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & ethnic_code == "UN")), "", "","" , count(filter(NEW_HANOVER_voters, party_cd == "DEM" & age_at_year_end <= "30")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & age_at_year_end <= "30")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & age_at_year_end <= "30")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & age_at_year_end > "64")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & age_at_year_end > "64")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & age_at_year_end > "64")), " ", " ", " ", count(filter(NEW_HANOVER_voters, party_cd == "DEM" & gender_code == "F")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & gender_code == "F")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & gender_code == "F")), count(filter(NEW_HANOVER_voters, party_cd == "DEM" & gender_code == "M")), count(filter(NEW_HANOVER_voters, party_cd == "REP" & gender_code == "M")), count(filter(NEW_HANOVER_voters, party_cd == "UNA" & gender_code == "M")), " ", " ", " "," ", " ", count(filter(NEW_HANOVER_voters))),ncol=3,byrow=TRUE)
colnames(NEW_HANOVER_stats) <- c("DEM", "REP", "UNA")
rownames(NEW_HANOVER_stats) <- c("ALL", "**race**","ASIAN","BLACK or AFRICAN AMERICAN", "AMERICAN INDIAN or ALASKA NATIVE",  "TWO or MORE RACES", "OTHER", "NATIVE HAWAIIAN or PACIFIC ISLANDER", "UNDESIGNATED", "WHITE", "**ethnicity**", "HISPANIC or LATINO", "NOT HISPANIC or NOT LATINO", "UNDESIGNATED", "**age**", "LESS 30", "BETWEEN 30 & 65","MORE 65", "**sex**","FEMALE", "MALE", "**count total**","TOTAL")
# NEW_HANOVER_stats <- as.table(NEW_HANOVER_stats)
NEW_HANOVER_stats
```

# RANDOLPH STATS
```{r}
RANDOLPH_stats <- matrix(c(count(filter(RANDOLPH_voters, party_cd == "DEM")), count(filter(RANDOLPH_voters, party_cd == "REP")), count(filter(RANDOLPH_voters, party_cd == "UNA")), '', '', '', count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "A")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "A")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "A")), count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "B")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "B")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "B")), count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "I")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "I")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "I")), count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "M")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "M")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "M")), count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "O")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "O")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "O")), count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "P")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "P")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "P")), count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "U")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "U")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "U")), count(filter(RANDOLPH_voters, party_cd == "DEM" & race_code == "W")), count(filter(RANDOLPH_voters, party_cd == "REP" & race_code == "W")), count(filter(RANDOLPH_voters, party_cd == "UNA" & race_code == "W")), " ", " ", " ", count(filter(RANDOLPH_voters, party_cd == "DEM" & ethnic_code == "HL")), count(filter(RANDOLPH_voters, party_cd == "REP" & ethnic_code == "HL")), count(filter(RANDOLPH_voters, party_cd == "UNA" & ethnic_code == "HL")), count(filter(RANDOLPH_voters, party_cd == "DEM" & ethnic_code == "NL")), count(filter(RANDOLPH_voters, party_cd == "REP" & ethnic_code == "NL")), count(filter(RANDOLPH_voters, party_cd == "UNA" & ethnic_code == "NL")), count(filter(RANDOLPH_voters, party_cd == "DEM" & ethnic_code == "UN")), count(filter(RANDOLPH_voters, party_cd == "REP" & ethnic_code == "UN")), count(filter(RANDOLPH_voters, party_cd == "UNA" & ethnic_code == "UN")), "", "","" , count(filter(RANDOLPH_voters, party_cd == "DEM" & age_at_year_end <= "30")), count(filter(RANDOLPH_voters, party_cd == "REP" & age_at_year_end <= "30")), count(filter(RANDOLPH_voters, party_cd == "UNA" & age_at_year_end <= "30")), count(filter(RANDOLPH_voters, party_cd == "DEM" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(RANDOLPH_voters, party_cd == "REP" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(RANDOLPH_voters, party_cd == "UNA" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(RANDOLPH_voters, party_cd == "DEM" & age_at_year_end > "64")), count(filter(RANDOLPH_voters, party_cd == "REP" & age_at_year_end > "64")), count(filter(RANDOLPH_voters, party_cd == "UNA" & age_at_year_end > "64")), " ", " ", " ", count(filter(RANDOLPH_voters, party_cd == "DEM" & gender_code == "F")), count(filter(RANDOLPH_voters, party_cd == "REP" & gender_code == "F")), count(filter(RANDOLPH_voters, party_cd == "UNA" & gender_code == "F")), count(filter(RANDOLPH_voters, party_cd == "DEM" & gender_code == "M")), count(filter(RANDOLPH_voters, party_cd == "REP" & gender_code == "M")), count(filter(RANDOLPH_voters, party_cd == "UNA" & gender_code == "M")), " ", " ", " "," ", " ", count(filter(RANDOLPH_voters))),ncol=3,byrow=TRUE)
colnames(RANDOLPH_stats) <- c("DEM", "REP", "UNA")
rownames(RANDOLPH_stats) <- c("ALL", "**race**","ASIAN","BLACK or AFRICAN AMERICAN", "AMERICAN INDIAN or ALASKA NATIVE",  "TWO or MORE RACES", "OTHER", "NATIVE HAWAIIAN or PACIFIC ISLANDER", "UNDESIGNATED", "WHITE", "**ethnicity**", "HISPANIC or LATINO", "NOT HISPANIC or NOT LATINO", "UNDESIGNATED", "**age**", "LESS 30", "BETWEEN 30 & 65","MORE 65", "**sex**","FEMALE", "MALE", "**count total**","TOTAL")
# RANDOLPH_stats <- as.table(RANDOLPH_stats)
RANDOLPH_stats
```

# ROBESON STATS
```{r}
ROBESON_stats <- matrix(c(count(filter(ROBESON_voters, party_cd == "DEM")), count(filter(ROBESON_voters, party_cd == "REP")), count(filter(ROBESON_voters, party_cd == "UNA")), '', '', '', count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "A")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "A")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "A")), count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "B")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "B")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "B")), count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "I")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "I")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "I")), count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "M")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "M")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "M")), count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "O")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "O")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "O")), count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "P")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "P")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "P")), count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "U")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "U")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "U")), count(filter(ROBESON_voters, party_cd == "DEM" & race_code == "W")), count(filter(ROBESON_voters, party_cd == "REP" & race_code == "W")), count(filter(ROBESON_voters, party_cd == "UNA" & race_code == "W")), " ", " ", " ", count(filter(ROBESON_voters, party_cd == "DEM" & ethnic_code == "HL")), count(filter(ROBESON_voters, party_cd == "REP" & ethnic_code == "HL")), count(filter(ROBESON_voters, party_cd == "UNA" & ethnic_code == "HL")), count(filter(ROBESON_voters, party_cd == "DEM" & ethnic_code == "NL")), count(filter(ROBESON_voters, party_cd == "REP" & ethnic_code == "NL")), count(filter(ROBESON_voters, party_cd == "UNA" & ethnic_code == "NL")), count(filter(ROBESON_voters, party_cd == "DEM" & ethnic_code == "UN")), count(filter(ROBESON_voters, party_cd == "REP" & ethnic_code == "UN")), count(filter(ROBESON_voters, party_cd == "UNA" & ethnic_code == "UN")), "", "","" , count(filter(ROBESON_voters, party_cd == "DEM" & age_at_year_end <= "30")), count(filter(ROBESON_voters, party_cd == "REP" & age_at_year_end <= "30")), count(filter(ROBESON_voters, party_cd == "UNA" & age_at_year_end <= "30")), count(filter(ROBESON_voters, party_cd == "DEM" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(ROBESON_voters, party_cd == "REP" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(ROBESON_voters, party_cd == "UNA" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(ROBESON_voters, party_cd == "DEM" & age_at_year_end > "64")), count(filter(ROBESON_voters, party_cd == "REP" & age_at_year_end > "64")), count(filter(ROBESON_voters, party_cd == "UNA" & age_at_year_end > "64")), " ", " ", " ", count(filter(ROBESON_voters, party_cd == "DEM" & gender_code == "F")), count(filter(ROBESON_voters, party_cd == "REP" & gender_code == "F")), count(filter(ROBESON_voters, party_cd == "UNA" & gender_code == "F")), count(filter(ROBESON_voters, party_cd == "DEM" & gender_code == "M")), count(filter(ROBESON_voters, party_cd == "REP" & gender_code == "M")), count(filter(ROBESON_voters, party_cd == "UNA" & gender_code == "M")), " ", " ", " "," ", " ", count(filter(ROBESON_voters))),ncol=3,byrow=TRUE)
colnames(ROBESON_stats) <- c("DEM", "REP", "UNA")
rownames(ROBESON_stats) <- c("ALL", "**race**","ASIAN","BLACK or AFRICAN AMERICAN", "AMERICAN INDIAN or ALASKA NATIVE",  "TWO or MORE RACES", "OTHER", "NATIVE HAWAIIAN or PACIFIC ISLANDER", "UNDESIGNATED", "WHITE", "**ethnicity**", "HISPANIC or LATINO", "NOT HISPANIC or NOT LATINO", "UNDESIGNATED", "**age**", "LESS 30", "BETWEEN 30 & 65","MORE 65", "**sex**","FEMALE", "MALE", "**count total**","TOTAL")
# ROBESON_stats <- as.table(ROBESON_stats)
ROBESON_stats
```

# SCOTLAND STATS
```{r}
SCOTLAND_stats <- matrix(c(count(filter(SCOTLAND_voters, party_cd == "DEM")), count(filter(SCOTLAND_voters, party_cd == "REP")), count(filter(SCOTLAND_voters, party_cd == "UNA")), '', '', '', count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "A")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "A")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "A")), count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "B")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "B")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "B")), count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "I")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "I")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "I")), count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "M")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "M")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "M")), count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "O")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "O")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "O")), count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "P")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "P")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "P")), count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "U")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "U")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "U")), count(filter(SCOTLAND_voters, party_cd == "DEM" & race_code == "W")), count(filter(SCOTLAND_voters, party_cd == "REP" & race_code == "W")), count(filter(SCOTLAND_voters, party_cd == "UNA" & race_code == "W")), " ", " ", " ", count(filter(SCOTLAND_voters, party_cd == "DEM" & ethnic_code == "HL")), count(filter(SCOTLAND_voters, party_cd == "REP" & ethnic_code == "HL")), count(filter(SCOTLAND_voters, party_cd == "UNA" & ethnic_code == "HL")), count(filter(SCOTLAND_voters, party_cd == "DEM" & ethnic_code == "NL")), count(filter(SCOTLAND_voters, party_cd == "REP" & ethnic_code == "NL")), count(filter(SCOTLAND_voters, party_cd == "UNA" & ethnic_code == "NL")), count(filter(SCOTLAND_voters, party_cd == "DEM" & ethnic_code == "UN")), count(filter(SCOTLAND_voters, party_cd == "REP" & ethnic_code == "UN")), count(filter(SCOTLAND_voters, party_cd == "UNA" & ethnic_code == "UN")), "", "","" , count(filter(SCOTLAND_voters, party_cd == "DEM" & age_at_year_end <= "30")), count(filter(SCOTLAND_voters, party_cd == "REP" & age_at_year_end <= "30")), count(filter(SCOTLAND_voters, party_cd == "UNA" & age_at_year_end <= "30")), count(filter(SCOTLAND_voters, party_cd == "DEM" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(SCOTLAND_voters, party_cd == "REP" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(SCOTLAND_voters, party_cd == "UNA" & age_at_year_end > "30" & age_at_year_end < "65")), count(filter(SCOTLAND_voters, party_cd == "DEM" & age_at_year_end > "64")), count(filter(SCOTLAND_voters, party_cd == "REP" & age_at_year_end > "64")), count(filter(SCOTLAND_voters, party_cd == "UNA" & age_at_year_end > "64")), " ", " ", " ", count(filter(SCOTLAND_voters, party_cd == "DEM" & gender_code == "F")), count(filter(SCOTLAND_voters, party_cd == "REP" & gender_code == "F")), count(filter(SCOTLAND_voters, party_cd == "UNA" & gender_code == "F")), count(filter(SCOTLAND_voters, party_cd == "DEM" & gender_code == "M")), count(filter(SCOTLAND_voters, party_cd == "REP" & gender_code == "M")), count(filter(SCOTLAND_voters, party_cd == "UNA" & gender_code == "M")), " ", " ", " "," ", " ", count(filter(SCOTLAND_voters))), ncol=3, byrow=TRUE)
colnames(SCOTLAND_stats) <- c("DEM", "REP", "UNA")
rownames(SCOTLAND_stats) <- c("ALL", "**race**","ASIAN","BLACK or AFRICAN AMERICAN", "AMERICAN INDIAN or ALASKA NATIVE",  "TWO or MORE RACES", "OTHER", "NATIVE HAWAIIAN or PACIFIC ISLANDER", "UNDESIGNATED", "WHITE", "**ethnicity**", "HISPANIC or LATINO", "NOT HISPANIC or NOT LATINO", "UNDESIGNATED", "**age**", "LESS 30", "BETWEEN 30 & 65","MORE 65", "**sex**","FEMALE", "MALE", "**count total**","TOTAL")
# SCOTLAND_stats <- as.table(SCOTLAND_stats)
SCOTLAND_stats
```

# Export data
```{r}
write.csv(DURHAM_stats , file = "DURHAM_stats.csv")
write.csv(MECKLENBURG_stats , file = "MECKLENBURG_stats.csv")
write.csv(NASH_stats , file = "NASH_stats.csv")
write.csv(`NEW_HANOVER_stats` , file = "NEW_HANOVER_stats.csv")
write.csv(RANDOLPH_stats , file = "RANDOLPH_stats.csv")
write.csv(ROBESON_stats , file = "ROBESON_stats.csv")
write.csv(SCOTLAND_stats , file = "SCOTLAND_stats.csv")
```